/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface DriverContainer {
        "age": string;
        "global": string;
        "name": string;
        "picture": string;
        "team": string;
    }
}
declare global {
    interface HTMLDriverContainerElement extends Components.DriverContainer, HTMLStencilElement {
    }
    var HTMLDriverContainerElement: {
        prototype: HTMLDriverContainerElement;
        new (): HTMLDriverContainerElement;
    };
    interface HTMLElementTagNameMap {
        "driver-container": HTMLDriverContainerElement;
    }
}
declare namespace LocalJSX {
    interface DriverContainer {
        "age"?: string;
        "global"?: string;
        "name"?: string;
        "picture"?: string;
        "team"?: string;
    }
    interface IntrinsicElements {
        "driver-container": DriverContainer;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "driver-container": LocalJSX.DriverContainer & JSXBase.HTMLAttributes<HTMLDriverContainerElement>;
        }
    }
}
